version: 2
jobs:
  publish:
    docker:
      - image: docker:17.12.1-ce
    working_directory: ~/git-sync
    steps:
      - checkout 
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          TAG=1.0.0
          docker build -t devatherock/git-sync:$TAG .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/git-sync:$TAG
      
workflows:
  version: 2
  docker_publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master

