version: 2
jobs:
  groovy_script_to_jar:
    docker:
      - image: devatherock/drone-groovy-script-to-jar:2.4-alpine
    working_directory: ~/git-sync
    environment:
      PLUGIN_SCRIPT_PATH: SyncGitRepos.groovy
    steps:
      - checkout
      - run: sh /scripts/entry-point.sh
      - persist_to_workspace:
          root: ~/git-sync
          paths:
            - SyncGitRepos.jar
  docker_build_dry_run:
    docker:
      - image: docker:17.12.1-ce
    working_directory: ~/git-sync
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ~/git-sync
      - run: docker build .
  publish:
    docker:
      - image: docker:17.12.1-ce
    working_directory: ~/git-sync
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - attach_workspace:
          at: ~/git-sync
      - run: |
          TAG=1.0.1
          docker build -t devatherock/git-sync:$TAG .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/git-sync:$TAG
            
workflows:
  version: 2
  build_publish:
    jobs:
      - groovy_script_to_jar:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - groovy_script_to_jar
  pr_check:
    jobs:
      - groovy_script_to_jar:
          filters:
            branches:
              ignore: master
      - docker_build_dry_run:
          requires:
            - groovy_script_to_jar
