docker_image: &docker_image
  docker:
    - image: docker:19.03.6
    
resource_class: &resource_class    
  resource_class: small
  
version: 2.1
jobs:
  groovy_script_to_jar:
    docker:
      - image: devatherock/drone-groovy-script-to-jar:2.5-alpine
    <<: *resource_class
    working_directory: ~/git-sync
    environment:
      PLUGIN_SCRIPT_PATH: SyncGitRepos.groovy
    steps:
      - checkout
      - run: sh /scripts/entry-point.sh
      - persist_to_workspace:
          root: ~/git-sync
          paths:
            - SyncGitRepos.jar
            
  docker_build_dry_run_circle:
    <<: *docker_image
    <<: *resource_class
    working_directory: ~/git-sync
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/git-sync
      - run: docker build -f docker/CircleCI.Dockerfile .
  docker_build_dry_run_drone:
    <<: *docker_image
    <<: *resource_class
    working_directory: ~/git-sync
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/git-sync
      - run: docker build -f docker/Drone.Dockerfile .
  docker_build_dry_run_vela:
    <<: *docker_image
    <<: *resource_class
    working_directory: ~/git-sync
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/git-sync
      - run: docker build -f docker/Vela.Dockerfile .
      
  publish_circle:
    <<: *docker_image
    <<: *resource_class
    working_directory: ~/git-sync
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/git-sync
      - run: |
          TAG=1.0.6
          docker build -t devatherock/git-sync:$TAG -f docker/CircleCI.Dockerfile .
          docker tag devatherock/git-sync:$TAG devatherock/git-sync:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/git-sync:$TAG
          docker push devatherock/git-sync:latest
  publish_drone:
    <<: *docker_image
    <<: *resource_class
    working_directory: ~/git-sync
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/git-sync
      - run: |
          TAG=1.0.6
          docker build -t devatherock/drone-git-sync:$TAG -f docker/Drone.Dockerfile .
          docker tag devatherock/drone-git-sync:$TAG devatherock/drone-git-sync:latest
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/drone-git-sync:$TAG
          docker push devatherock/drone-git-sync:latest
  publish_vela:
    <<: *docker_image
    <<: *resource_class
    working_directory: ~/git-sync
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: ~/git-sync
      - run: |
          TAG=1.0.6
          docker build -t devatherock/vela-git-sync:$TAG -f docker/Vela.Dockerfile .
          docker tag devatherock/vela-git-sync:$TAG devatherock/vela-git-sync:latest 
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push devatherock/vela-git-sync:$TAG
          docker push devatherock/vela-git-sync:latest
          
  notify:
    docker:
      - image: devatherock/simple-slack:0.3.0
    <<: *resource_class  
    environment:
      PARAMETER_TEXT: "{{.CircleBuildUrl}} by {{.CircleUsername}}"
    steps:
      - run:
          name: Success notification
          command: /bin/simpleslack -c "#33ad7f"
          when: on_success
      - run:
          name: Failure notification
          command: /bin/simpleslack -c "#a1040c"
          when: on_fail        

workflows:
  version: 2
  build_publish:
    jobs:
      - groovy_script_to_jar:
          filters:
            branches:
              only: master
      - publish_circle:
          requires:
            - groovy_script_to_jar
      - publish_drone:
          requires:
            - groovy_script_to_jar
      - publish_vela:
          requires:
            - groovy_script_to_jar
      - notify:
          requires:
            - publish_circle
            - publish_drone
            - publish_vela
  pr_check:
    jobs:
      - groovy_script_to_jar:
          filters:
            branches:
              ignore: master
      - docker_build_dry_run_circle:
          requires:
            - groovy_script_to_jar
      - docker_build_dry_run_drone:
          requires:
            - groovy_script_to_jar
      - docker_build_dry_run_vela:
          requires:
            - groovy_script_to_jar
